# Generated by Django 4.2.7 on 2024-05-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_frequentlyaskedquestion_topsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessGoal',
        ),
    ]
