# Generated by Django 4.2.7 on 2024-05-04 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goal', models.CharField(choices=[('LOSS', 'Weight Loss'), ('GAIN', 'Muscle Building'), ('FIT', 'Stay Fit')], max_length=100)),
                ('medical_history', models.CharField(max_length=100)),
                ('physical_activity_level', models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=100)),
                ('dietary_preferences', models.CharField(max_length=100)),
                ('fitness_environment', models.CharField(choices=[('Home', 'Home'), ('Gym', 'Gym'), ('Outside', 'Outside'), ('Studio', 'Studio')], max_length=100)),
                ('tracking_method', models.CharField(choices=[('Pen Paper', 'Pen Paper'), ('Fitness App', 'Fitness App'), ('Wearable Device', 'Wearable Device'), ('Personal Trainer', 'Personal Trainer')], max_length=100)),
                ('time_commitment', models.CharField(choices=[('1-2', '1-2 hours per week'), ('3-4', '3-4 hours per week'), ('5-7', '5-7 hours per week'), ('7+', 'more than 7 hours week')], max_length=100)),
                ('challenges', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
