# Generated by Django 4.2.7 on 2024-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dietary_preferences',
            new_name='nutritional_preferences',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fitness_goal',
            new_name='primary_fitness_goal',
        ),
    ]
